variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

default:
  image: gradle:8.13-jdk17
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths: [APIcred/.gradle/]

.gradle-job:
  before_script:
    - cd APIcred

stages:
  - build
  - test
  - sonar
  - deploy

build:
  extends: .gradle-job
  stage: build
  script: ./gradlew build -x test
  artifacts:
    paths:
      - APIcred/build/test-results/test
      - APIcred/build/reports/jacoco/
      - APIcred/build/classes/java/main
      - APIcred/build/libs/
    expire_in: 1 hour

test:
  extends: .gradle-job
  stage: test
  script: ./gradlew test jacocoTestReport
  artifacts:
    reports:
      junit: APIcred/build/test-results/test/TEST-*.xml
    paths:
      - APIcred/build/reports/jacoco/
      - APIcred/build/test-results/test
      - APIcred/build/classes/java/test
    expire_in: 1 hour

sonar:
  extends: .gradle-job
  stage: sonar
  dependencies: ["build", "test"]
  script:
    - ./gradlew compileJava compileTestJava
    - ./gradlew sonar
  variables:
    SONAR_HOST_URL: "http://localhost:9000"
    SONAR_TOKEN: "sqp_90f94c8d50d64056ae6ffd08d3532d01e8f0c3fe"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  allow_failure: true

docker:
  stage: deploy
  image: docker:24-cli
  services: [docker:24-dind]
  script:
    - docker build -t replan .
    - docker run -d -p 8080:8080 --name replan-app --rm replan
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "develop"