variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - docker

build:
  stage: build
  before_script:
    - git config --global --add safe.directory "$CI_PROJECT_DIR"
    - echo "JAVA Version:"
    - java -version
    - echo "Git Version:"
    - git --version
    - echo "PATH:"
    - echo $env:PATH
    - echo "JAVA_HOME:"
    - echo $env:JAVA_HOME

  script:
    - Set-Location APIcred
    - .\gradlew.bat bootJar
  artifacts:
    paths:
      - APIcred/build/libs/

test:
  stage: test
  script:
    - Set-Location APIcred
    - .\gradlew.bat test

docker:
  stage: docker
  script:
    - Set-Location APIcred
    - .\gradlew.bat build
    - Set-Location ..
    - docker build -t replan .
    - docker run -d -p 8080:8080 --name replanBE replan