variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build-test
  - sonar
  - docker


build-and-test:
  stage: build-test
  before_script:
    - git config --global --add safe.directory "$env:CI_PROJECT_DIR"
  script:
    - cd APIcred
    - .\gradlew.bat clean build test jacocoTestReport
  artifacts:
    paths:
      - APIcred/build/libs/*.jar
      - APIcred/build/reports/jacoco/
    expire_in: 1 hour
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - APIcred/.gradle/wrapper
      - APIcred/.gradle/caches


sonar:
  stage: sonar
  dependencies:
    - build-and-test
  before_script:
    - git config --global --add safe.directory "$env:CI_PROJECT_DIR"
  script:
    - cd APIcred
    - .\gradlew.bat sonar -x test -x build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "master"
  variables:
    SONAR_HOST_URL: "http://localhost:9000"
    SONAR_TOKEN: "sqp_3d2af99752301f76dd0cce3504772fdccc2197cb"
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - APIcred/.gradle/wrapper
      - APIcred/.gradle/caches
    policy: pull
  allow_failure: true


docker-build:
  stage: docker
  dependencies:
    - build-and-test
  before_script:
    - git config --global --add safe.directory "$env:CI_PROJECT_DIR"
  script:
    - docker build -t replan .
    - docker run -d -p 8080:8080 --name replanBE replan
    - Start-Sleep -Seconds 10
    - docker stop replanBE
    - docker rm replanBE
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"