variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test

build:
  stage: build
  script:
    - Set-Location APIcred
    - .\gradlew.bat assemble


test:
  stage: test
  script:
    - .\gradlew test

