variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonar
  - docker


before_script:
  - git config --global --add safe.directory C:/GitLab-Runner/builds/9TQ6CwjQZ/0/I523343/sem3-backend

build:
  stage: build
  script:
    - cd APIcred
    - ./gradlew bootJar
  artifacts:
    paths:
      - APIcred/build/libs/

test:
  stage: test
  script:
    - cd APIcred
    - ./gradlew test

sonarqube:
  stage: sonar
  image: gradle:8.3-jdk17
  script:
    - cd APIcred
    - ./gradlew test jacocoTestReport sonar
  only:
    - merge_requests
    - main
    - master
  allow_failure: true
  variables:
    SONAR_HOST_URL: "http://host.docker.internal:9000"
    SONAR_TOKEN: "sqp_3d2af99752301f76dd0cce3504772fdccc2197cb"
docker:
  stage: docker
  script:
    - cd APIcred
    - ./gradlew build
    - cd ..
    - docker build -t replan .
    - docker run -d -p 8080:8080 --name replanBE replan
