variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - docker

build:
  stage: build
  script:
    - Set-Location APIcred
    - .\gradlew.bat assemble


test:
  stage: test
  script:
    - Set-Location APIcred
    - .\gradlew.bat test

docker:
  stage: docker
  script:
    - Set-Location APIcred
    - .\gradlew.bat build
    - Set-Location ..
    - docker build -t replan .
    - docker run -d -p 8080:8080 --name replanBE replan