services:
  dev-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: team_platform
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:9
    depends_on:
      dev-db:
        condition: service_healthy
    volumes:
      - ./flyway/sql:/flyway/sql
    command:
      - -connectRetries=10
      - -url=jdbc:mysql://dev-db:3306/team_platform?allowPublicKeyRetrieval=true&useSSL=false
      - -user=root
      - -password=root
      - migrate

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      dev-db:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dev-db:3306/team_platform?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: ${JWT_SECRET:-iamafanofhakozbealzbecauseshesverycoolandfunnyandaustralianbutalsothesongsareagreat}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  db-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: